steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/truchiwoman/flask-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/truchiwoman/flask-app']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'flask-app', '--image', 'gcr.io/truchiwoman/flask-app', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated',]
images:
- 'gcr.io/truchiwoman/flask-app'
